# Generated by Django 4.0.1 on 2022-01-24 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=30)),
                ('preço', models.FloatField()),
                ('estoque', models.IntegerField()),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('cep', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('endereço', models.CharField(max_length=25)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=15)),
                ('bairro', models.CharField(max_length=25)),
                ('cidade', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=20)),
                ('id_usuario', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'endereco',
            },
        ),
    ]
